### ISSUE TITLE
Formula of black iron powder

### ISSUE THREAD

**Issue by ES-BitJump** [tracer4b/nomi-ceu#188]
Software package version: 1.4.2
Problem: JEI added the formula to make black iron powder. JEI could not identify red coal. There was sufficient red coal in the inventory, indicating the lack of raw materials. Adding the formula again and restarting the game could not solve the problem. It was judged that it might be the NBT identification problem of red coal

**Comment by Folanlron** [comment]
There should be a temporary recipe for a darkened "Red Coal"

But honestly Update it has been fixed for some time now..

**Comment by ES-BitJump** [comment]
After updating to 1.4.3, it still cannot be recognized “Red Coal”
